#!/bin/sh

opcode=deploy
while [ $# -gt 0 ]
do
	case $1 in
	-d|--destroy)
		opcode=destroy
		;;
	*)
		echo "option '$1' not supported!"
		exit 1
	esac
	shift
done

. ./.config

slaves=(${config_slaves//,/ })

if [ "${#slaves[@]}" -gt 0 ]; then
	if [ -z "$config_master" ]; then
		echo "invalid .config file!"
		exit 1
	fi
	master=$config_master
	mode="cluster"
else
	if [ -n "$config_master" ]; then
		master="$config_master"
	else	
		master="localhost"
	fi
	mode="pseudo"
fi

hosts=($master ${slaves[@]})

if [ -n "$config_user" ]; then
	user=$config_user
else
	user=$USER
fi

#echo "Deploying MDH ($mode mode)"
echo "Cluster nodes:"
i=0
for host in ${hosts[@]}
do
	((i++))
	echo "[$i] $host"
done

if [ $opcode = 'deploy' ]; then
	for host in ${hosts[@]}
	do
		ssh-copy-id $host
	done

	temp=`mktemp -d`
	# copy mdh
	cp -r $PWD $temp
	wd=$temp/`basename $PWD`
	# generate ssh key if cluster mode
	if [ $mode = 'cluster' ]; then
		pk=$temp/ssh/id_rsa
		mkdir -p `dirname $pk`
		ssh-keygen -P '' -C "$user@$master" -f $pk || exit 1
	fi

	total=${#hosts[@]}
	for ((i=0; i<$total;i++))
	do
		host=${hosts[$i]}
		echo "[$((i+1))/$total] $host"
		scp -q -r $temp $user@$host:/tmp/
		if [ $mode = 'cluster' ]; then
			options="--id $i --key $pk.pub --master $master --slave $config_slaves"
		fi
		ssh $user@$host sudo $wd/deploy-one $options || exit 1
		ssh $user@$host rm -rf $temp
		echo
	done

	rm -rf $temp

	for app in $app_seq
	do
		ssh $user@$master sudo service $app start || exit 1
		if [ $app = 'hadoop' ]; then
			ssh $user@$master sudo service $app init || exit 1
		fi
	done
else
	app_rev=""
	for app in $app_seq
	do
		app_rev="$app $app_rev"
	done

	for app in $app_rev
	do
		ssh $user@$master sudo service $app stop || exit 1
	done

	for host in ${hosts[@]}	
	do
		# FIXME
		ssh $user@$host sudo /opt/mdh/destroy || exit 1
	done
fi
