#!/bin/sh

function hadoop_destroy
{
	rm -rf /var/log/$hadoop_user
	sed -i '/HADOOP_/d' $profile
}

function zookeeper_destroy
{
	sed -i '/ZOOKEEPER_HOME/d' $profile
	sudo -u $hadoop_user rm -rf $zk_data_dir
}

function hbase_destroy
{
	sed -i '/HBASE_HOME/d' $profile
}

function spark_destroy
{
	sed -i '/SPARK_/d' $profile
}

if [ $UID -ne 0 ]; then
	echo "pls run as root!"
	exit 1
fi

echo "Removing MDH ..."

. /etc/mdh.conf

for app in $app_rev
do
	if [ -e /etc/init.d/$app ]; then
		echo "removing $app ..."
		service $app stop || exit 1
		rm -f /etc/init.d/$app
		${app}_destroy
		rm -rf $"$app"_home
	fi
done

rm -rf $util_root || exit 1

rm -f $profile # FIXME

rm -rf $mdh_root || exit 1


userdel -r $hadoop_user || exit 1

rm -f /etc/mdh.conf

echo "MDH removed successfully!"
echo
