#!/bin/sh

src=$1
dst=$2

if [ -d $src ]; then
	wd=`basename $src`
	temp=`mktemp -d`

	echo -n "copying $wd -> $dst ."
	cp -r $src $temp || exit 1
	echo -n .
	cd $temp && tar cf $wd.tar $wd || exit 1
	echo -n .
	scp -q $wd.tar $dst: || exit 1
	echo -n .
	rm -rf $temp
	echo -n .
	ssh $dst rm -rf $wd
	echo -n .
	ssh $dst tar xf $wd.tar
	echo -n .
	ssh $dst rm -f $wd.tar
	echo " done"
else
	echo "copying $src -> $dst ..."
	scp $src $dst:
fi
