#!/bin/sh

. /etc/mdh.conf

if [ -z "$HADOOP_HOME" ]; then
	HADOOP_HOME=$mdh_root/hadoop
fi

case $1 in
start)
	sudo -u $hadoop_user $HADOOP_HOME/sbin/start-dfs.sh || exit 1
	sudo -u $hadoop_user $HADOOP_HOME/sbin/start-yarn.sh || exit 1
	sudo -u $hadoop_user $HADOOP_HOME/sbin/mr-jobhistory-daemon.sh start historyserver || exit 1
	;;
stop)
	sudo -u $hadoop_user $HADOOP_HOME/sbin/mr-jobhistory-daemon.sh stop historyserver || exit 1
	sudo -u $hadoop_user $HADOOP_HOME/sbin/stop-dfs.sh || exit 1
	sudo -u $hadoop_user $HADOOP_HOME/sbin/stop-yarn.sh || exit 1
	;;
init)
	sudo -u $hadoop_user $HADOOP_HOME/bin/hadoop fs -mkdir -p /tmp /user || exit 1
	sudo -u $hadoop_user $HADOOP_HOME/bin/hadoop fs -chmod g+w /tmp /user || exit 1
	sudo -u $hadoop_user $HADOOP_HOME/bin/hadoop fs -ls / || exit 1
	;;
*)
	echo "Usage: service `basename $0` {start|stop|init}"
	exit 1
	;;
esac
