#!/bin/sh

. /etc/mdh.conf

if [ -z "$HBASE_HOME" ]; then
	HBASE_HOME=$mdh_root/hbase
fi

case $1 in
start|stop)
	sudo -u $hadoop_user $HBASE_HOME/bin/$1-hbase.sh
	;;
*)
	echo "Usage: service `basename $0` {start|stop}"
	exit 1
	;;
esac
